[book]
authors = ["KevinZonda"]
language = "zh"
multilingual = false
src = "."
title = "机器学习书：以高中数学视角"

[preprocessor.chapter-number]
renderer = ["html"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.katex]
after = ["links"]
# KaTeX options.
output = "html"
leqno = false
fleqn = false
throw-on-error = true
error-color = "#cc0000"
min-rule-thickness = -1.0
max-size = "Infinity"
max-expand = 1000
trust = false
# Extra options.
no-css = false
include-src = false
block-delimiter = { left = "$$", right = "$$" }
inline-delimiter = { left = "$", right = "$" }
pre-render = true

[preprocessor.open-on-gh]
command = "mdbook-open-on-gh"
renderer = ["html"]

[preprocessor.admonish]
command = "mdbook-admonish"
assets_version = "3.0.2"

[preprocessor.pagetoc]

[output.html]
additional-js = [
    "mermaid.min.js", "mermaid-init.js", # mermaid
    "theme/pagetoc.js"
]

#pagetoc
additional-css = [
    "theme/pagetoc.css",
    "theme/mdbook-admonish.css"
]

# open-on-gh
git-repository-url = "https://github.com/KevinZonda/MLBook"
git-branch = "master"
open-on-text = "找到了问题？[在 GitHub 上编辑这个页面]"
