name: mdbook

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Dependency
      run: |
        cd ..
        mkdir dep
        cd dep
        wget https://ftp.kevinzonda.com/dist/mdbook-katex%400.8.0-x64/mdbook-katex
        wget https://ftp.kevinzonda.com/dist/mdbook%400.4.37-x64/mdbook
        chmod +x *
        echo "$(pwd)" >> $GITHUB_PATH
        cd ../MLBook
        
    - name: Build book
      run: |
        chmod +x preprocess.sh
        sh ./preprocess.sh
        mdbook build --dest-dir ../out
        git reset --hard HEAD
    
    - name: Patch dist
      run: |
        rm -rf ../out/.git
        rm -rf ../out/*.py
        rm -rf ../out/*.sh

        commit=$(git rev-parse HEAD)
        branch=$(git rev-parse --abbrev-ref HEAD)

        echo $commit >  ../out/COMMIT.html
        echo $branch >  ../out/HEAD.html
        echo $branch >> ../out/GIT_INFO.html
        echo $commit >  ../out/GIT_INFO.html
        echo 'pong'  >  ../out/ping.html

    - name: Deploy
      run: |
        git fetch
        git pull --force
        
        git checkout gh-pages
        git fetch
        git pull --force
        git config user.name KevinZonda
        git config user.email 33132228+KevinZonda@users.noreply.github.com
        ls | grep -xv ".git" | xargs rm -fr
        mv ../out/* .
        echo 1 >> .nojekyll
        echo mlbook.dev > CNAME
        git add .
        git commit -m "S.C.: `date "+%Y-%m-%d %H:%M:%S UTC%:z"`" || true
        git push
