name: Rust

on:
  push:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Install Dependency
      run: |
        mkdir dep
        cd dep
        wget https://ftp.kevinzonda.com/dist/mdbook-katex%400.8.0-x64/mdbook-katex
        wget https://ftp.kevinzonda.com/dist/mdbook%400.4.37-x64/mdbook
        cd ..
        echo "$(pwd)/dep" >> $GITHUB_PATH
        
    - name: Build book
      run: |
        mdbook build --dest-dir out

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: out
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
